import { Chat } from "@/types/chat";
import { Message } from "@/types/message";

// Helper to create dates relative to now
const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60 * 1000);
const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 60 * 60 * 1000);
const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000);

export const mockChats: Chat[] = [
  {
    id: "1",
    name: "Lucas",
    lastMessage:
      "By the way, I’ll also need a new website for my Ideal & Milk business. How soon can we start?",
    lastMessageTime: daysAgo(0),
    unreadCount: 0,
    isPinned: true,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: true,
  },
  {
    id: "2",
    name: "Grandma Star",
    lastMessage: "Voice call",
    lastMessageTime: hoursAgo(2),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "3",
    name: "+501 624-2755",
    lastMessage: "Hey...",
    lastMessageTime: daysAgo(1),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "4",
    name: "WhatsApp",
    lastMessage: "New: Set the mood with status reaction stick...",
    lastMessageTime: daysAgo(1),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "5",
    name: "+501 608-2077 (You)",
    lastMessage: "Photo",
    lastMessageTime: daysAgo(2),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "6",
    name: "Jaredd",
    lastMessage: "No not yet",
    lastMessageTime: daysAgo(2),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "7",
    name: "Sarah",
    lastMessage: "Thanks for the update!",
    lastMessageTime: daysAgo(3),
    unreadCount: 2,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: true,
  },
  {
    id: "8",
    name: "Project Team",
    lastMessage: "Meeting at 3 PM",
    lastMessageTime: daysAgo(3),
    unreadCount: 5,
    isPinned: false,
    isArchived: false,
    isGroup: true,
    isMuted: true,
    isOnline: false,
  },
  {
    id: "9",
    name: "Alex",
    lastMessage: "See you tomorrow",
    lastMessageTime: daysAgo(4),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "10",
    name: "Emma Johnson",
    lastMessage: "That sounds great!",
    lastMessageTime: daysAgo(5),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: true,
  },
  {
    id: "11",
    name: "Family Group",
    lastMessage: "Don't forget dinner on Sunday",
    lastMessageTime: daysAgo(5),
    unreadCount: 3,
    isPinned: false,
    isArchived: false,
    isGroup: true,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "12",
    name: "Michael",
    lastMessage: "Perfect, let's do it",
    lastMessageTime: daysAgo(6),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "13",
    name: "Lisa",
    lastMessage: "Can you send me the files?",
    lastMessageTime: daysAgo(7),
    unreadCount: 1,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "14",
    name: "Gym Buddies",
    lastMessage: "Tomorrow morning at 6?",
    lastMessageTime: daysAgo(8),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: true,
    isMuted: true,
    isOnline: false,
  },
  {
    id: "15",
    name: "David Chen",
    lastMessage: "Awesome work!",
    lastMessageTime: daysAgo(9),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
];

// Mock messages for the main chat (Mum)
export const mockMessages: Record<string, Message[]> = {
  "1": [
    {
      id: "m1",
      chatId: "1",
      content: "Ok",
      timestamp: new Date(2026, 0, 9, 9, 36, 0),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m2",
      chatId: "1",
      content:
        "Hey, I just went through everything. Really solid work 👏 I like how clean and fast everything feels.",
      timestamp: new Date(2026, 0, 9, 9, 39, 0),
      isOwnMessage: false,
    },
    {
      id: "m3",
      chatId: "1",
      content: "Thanks a lot, Lucas! Glad it worked out well for you.",
      timestamp: new Date(2026, 0, 9, 9, 48, 0),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m4",
      chatId: "1",
      content: "Witcho",
      timestamp: new Date(2026, 0, 9, 12, 10, 0),
      isOwnMessage: false,
    },
    {
      id: "m5",
      chatId: "1",
      content: "Where dady left his kit bag now",
      timestamp: new Date(2026, 0, 9, 12, 10, 0),
      isOwnMessage: false,
    },
    {
      id: "m6",
      chatId: "1",
      content: "Here at the house",
      timestamp: new Date(2026, 0, 9, 12, 11, 0),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m7",
      chatId: "1",
      content: "I just reach",
      timestamp: new Date(2026, 0, 9, 12, 11, 0),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m8",
      chatId: "1",
      content:
        "Hum well if he stay with u dont worry ill live with grandma only me and jo .estrlla them will stay and live here",
      timestamp: new Date(2026, 0, 9, 12, 12, 0),
      isOwnMessage: false,
    },
    {
      id: "m9",
      chatId: "1",
      content:
        "Dont chase him beca you no yr dad has been good to uno too just that he need to fine God and only so he will be a better dad.",
      timestamp: new Date(2026, 0, 9, 12, 13, 0),
      isOwnMessage: false,
    },
    {
      id: "m10",
      chatId: "1",
      content: "I won't don't worry",
      timestamp: new Date(2026, 0, 9, 12, 53, 0),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m11",
      chatId: "1",
      content: "Wicho is dady there",
      timestamp: new Date(2026, 0, 9, 19, 30, 0),
      isOwnMessage: false,
    },
    {
      id: "m12",
      chatId: "1",
      content:
        "Actually, I’ll also need a new website for my Ideal & Milk business. Oh and I need it by yesterday.",
      timestamp: new Date(2026, 0, 9, 13, 0, 0),
      isOwnMessage: false,
    },
    // {
    //   id: "m13",
    //   chatId: "1",
    //   content: "No",
    //   timestamp: new Date(2026, 0, 9, 19, 44, 0),
    //   isOwnMessage: true,
    //   status: "read",
    // },
  ],
  "2": [
    {
      id: "m14",
      chatId: "2",
      content: "Hey Grandma! How are you?",
      timestamp: hoursAgo(3),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m15",
      chatId: "2",
      content: "I'm doing well, thank you dear",
      timestamp: hoursAgo(2.5),
      isOwnMessage: false,
    },
  ],
  "7": [
    {
      id: "m16",
      chatId: "7",
      content: "Did you finish the report?",
      timestamp: daysAgo(3),
      isOwnMessage: false,
    },
    {
      id: "m17",
      chatId: "7",
      content: "Yes, just sent it over!",
      timestamp: daysAgo(3),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m18",
      chatId: "7",
      content: "Thanks for the update!",
      timestamp: daysAgo(3),
      isOwnMessage: false,
    },
  ],
};
