import { Chat } from "@/types/chat";
import { Message } from "@/types/message";

// Helper to create dates relative to now
const minutesAgo = (minutes: number) =>
  new Date(Date.now() - minutes * 60 * 1000);
const hoursAgo = (hours: number) =>
  new Date(Date.now() - hours * 60 * 60 * 1000);
const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000);

export const mockChats: Chat[] = [
  {
    id: "1",
    name: "Lucas",
    lastMessage:
      "By the way, I'll also need a new website for my Ideal & Milk business. How soon can we start?",
    lastMessageTime: hoursAgo(3),
    unreadCount: 0,
    isPinned: true,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: true,
  },
  {
    id: "7",
    name: "Sarah",
    lastMessage: "Thanks for the update!",
    lastMessageTime: daysAgo(3),
    unreadCount: 2,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: true,
  },
  {
    id: "8",
    name: "Project Team",
    lastMessage: "Meeting at 3 PM",
    lastMessageTime: daysAgo(3),
    unreadCount: 5,
    isPinned: false,
    isArchived: false,
    isGroup: true,
    isMuted: true,
    isOnline: false,
  },
  {
    id: "9",
    name: "Alex",
    lastMessage: "See you tomorrow",
    lastMessageTime: daysAgo(4),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "10",
    name: "Emma Johnson",
    lastMessage: "That sounds great!",
    lastMessageTime: daysAgo(5),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: true,
  },
  {
    id: "11",
    name: "Family Group",
    lastMessage: "Don't forget dinner on Sunday",
    lastMessageTime: daysAgo(5),
    unreadCount: 3,
    isPinned: false,
    isArchived: false,
    isGroup: true,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "12",
    name: "Michael",
    lastMessage: "Perfect, let's do it",
    lastMessageTime: daysAgo(6),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "13",
    name: "Lisa",
    lastMessage: "Can you send me the files?",
    lastMessageTime: daysAgo(7),
    unreadCount: 1,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
  {
    id: "14",
    name: "Gym Buddies",
    lastMessage: "Tomorrow morning at 6?",
    lastMessageTime: daysAgo(8),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: true,
    isMuted: true,
    isOnline: false,
  },
  {
    id: "15",
    name: "David Chen",
    lastMessage: "Awesome work!",
    lastMessageTime: daysAgo(9),
    unreadCount: 0,
    isPinned: false,
    isArchived: false,
    isGroup: false,
    isMuted: false,
    isOnline: false,
  },
];

// Mock messages for the main chat (Mum)
export const mockMessages: Record<string, Message[]> = {
  "1": [
    {
      id: "m1",
      chatId: "1",
      content: "Ok",
      timestamp: new Date(2026, 0, 9, 9, 36, 0),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m2",
      chatId: "1",
      content:
        "Hey, I just went through everything. Really solid work 👏 I like how clean and fast everything feels.",
      timestamp: new Date(2026, 0, 9, 9, 39, 0),
      isOwnMessage: false,
    },
    {
      id: "m3",
      chatId: "1",
      content: "Thanks a lot, Lucas! Glad it worked out well for you.",
      timestamp: new Date(2026, 0, 9, 9, 48, 0),
      isOwnMessage: true,
      status: "read",
    },
  ],
  "7": [
    {
      id: "m16",
      chatId: "7",
      content: "Did you finish the report?",
      timestamp: daysAgo(3),
      isOwnMessage: false,
    },
    {
      id: "m17",
      chatId: "7",
      content: "Yes, just sent it over!",
      timestamp: daysAgo(3),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m18",
      chatId: "7",
      content: "Thanks for the update!",
      timestamp: daysAgo(3),
      isOwnMessage: false,
    },
  ],
  "8": [
    {
      id: "m19",
      chatId: "8",
      content: "Hey team, don't forget about the meeting today",
      timestamp: daysAgo(3),
      isOwnMessage: false,
    },
    {
      id: "m20",
      chatId: "8",
      content: "What time again?",
      timestamp: daysAgo(3),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m21",
      chatId: "8",
      content: "Meeting at 3 PM",
      timestamp: daysAgo(3),
      isOwnMessage: false,
    },
  ],
  "9": [
    {
      id: "m22",
      chatId: "9",
      content: "Hey! Are we still on for coffee?",
      timestamp: daysAgo(4),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m23",
      chatId: "9",
      content: "Absolutely! Looking forward to it",
      timestamp: daysAgo(4),
      isOwnMessage: false,
    },
    {
      id: "m24",
      chatId: "9",
      content: "See you tomorrow",
      timestamp: daysAgo(4),
      isOwnMessage: false,
    },
  ],
  "10": [
    {
      id: "m25",
      chatId: "10",
      content: "I have an idea for the new project",
      timestamp: daysAgo(5),
      isOwnMessage: false,
    },
    {
      id: "m26",
      chatId: "10",
      content: "I'd love to hear it!",
      timestamp: daysAgo(5),
      isOwnMessage: true,
      status: "delivered",
    },
    {
      id: "m27",
      chatId: "10",
      content: "That sounds great!",
      timestamp: daysAgo(5),
      isOwnMessage: false,
    },
  ],
  "11": [
    {
      id: "m28",
      chatId: "11",
      content: "Everyone remember dinner this Sunday",
      timestamp: daysAgo(5),
      isOwnMessage: false,
    },
    {
      id: "m29",
      chatId: "11",
      content: "What should I bring?",
      timestamp: daysAgo(5),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m30",
      chatId: "11",
      content: "Don't forget dinner on Sunday",
      timestamp: daysAgo(5),
      isOwnMessage: false,
    },
  ],
  "12": [
    {
      id: "m31",
      chatId: "12",
      content: "Want to grab lunch this week?",
      timestamp: daysAgo(6),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m32",
      chatId: "12",
      content: "Yes! How about Thursday?",
      timestamp: daysAgo(6),
      isOwnMessage: false,
    },
    {
      id: "m33",
      chatId: "12",
      content: "Perfect, let's do it",
      timestamp: daysAgo(6),
      isOwnMessage: false,
    },
  ],
  "13": [
    {
      id: "m34",
      chatId: "13",
      content: "Hey Lisa, how's the project going?",
      timestamp: daysAgo(7),
      isOwnMessage: true,
      status: "delivered",
    },
    {
      id: "m35",
      chatId: "13",
      content: "Good! Almost done",
      timestamp: daysAgo(7),
      isOwnMessage: false,
    },
    {
      id: "m36",
      chatId: "13",
      content: "Can you send me the files?",
      timestamp: daysAgo(7),
      isOwnMessage: false,
    },
  ],
  "14": [
    {
      id: "m37",
      chatId: "14",
      content: "Who's in for tomorrow's workout?",
      timestamp: daysAgo(8),
      isOwnMessage: false,
    },
    {
      id: "m38",
      chatId: "14",
      content: "I'm in! 💪",
      timestamp: daysAgo(8),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m39",
      chatId: "14",
      content: "Tomorrow morning at 6?",
      timestamp: daysAgo(8),
      isOwnMessage: false,
    },
  ],
  "15": [
    {
      id: "m40",
      chatId: "15",
      content: "Just finished reviewing your presentation",
      timestamp: daysAgo(9),
      isOwnMessage: false,
    },
    {
      id: "m41",
      chatId: "15",
      content: "How did it look?",
      timestamp: daysAgo(9),
      isOwnMessage: true,
      status: "read",
    },
    {
      id: "m42",
      chatId: "15",
      content: "Awesome work!",
      timestamp: daysAgo(9),
      isOwnMessage: false,
    },
  ],
};
